### ISSUE TITLE
ライセンスファイルの追加

### ISSUE THREAD

**Issue by eitsupi** [statditto/quarto-revealjs-budoux#1]
素晴らしい拡張機能を作成していただきありがとうございます。
ぜひ使いたいと思うので、ライセンスファイルを追加していただけないでしょうか？
（Quarto拡張機能はソースコードに含めなければならないため、ライセンスが明確でないと採用しづらいと感じていますです）

**Comment by statditto** [comment]
ご指摘いただきありがとうございます！
普段コードを公開する機会がなかったため失念していました。Apache License 2.0を適用します。

**Comment by eitsupi** [comment]
早速対応していただきありがとうございます。

**Comment by statditto** [comment]
いえ、こちらこそ最初から記述しておくべき内容でしたのでコメントいただいて助かりました！
（全く話は変わりますが、いつもLTやブログ記事などで勉強させていただいてます！これからもよろしくお願いします🙇）
